---
- name: Check books
  fail:
    msg: No books variable provided
  when: books is not defined
- name: Show books
  debug:
    msg: "ISBN: {{ book.key }} Book: {{ book.value.title }} Author: {{ book.value.author }}"
  loop: "{{ books|dict2items }}"
  loop_control:
    loop_var: book
- name: Show books as XML
  debug:
    msg: "{{ lookup('template', role_path + '/files/book-report.xml.j2') }}"
