---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-xml
  - id: check-yaml
    args: [ '--allow-multiple-documents', '--unsafe' ]
    exclude: |
      (?x)^(
          .*/templates/.*.yaml|
          .*.template.yaml
      )$
  - id: check-toml
  - id: check-json
  - id: check-added-large-files
  - id: check-case-conflict
  - id: detect-aws-credentials
  - id: detect-private-key
  - id: check-executables-have-shebangs
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.12
  hooks:
  - id: terraform-fmt
  - id: terraform-validate
  - id: tflint
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.4
  hooks:
  - id: forbid-binary
  - id: git-check
  - id: markdownlint
  - id: require-ascii
  - id: shellcheck
  - id: shfmt
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.25.0
  hooks:
  - id: yamllint
    entry: yamllint --strict
- repo: https://github.com/ansible/ansible-lint.git
  rev: v4.3.7
  hooks:
  - id: ansible-lint
    files: \.(yaml|yml)$
- repo: https://gitlab.com/pycqa/flake8.git
  rev: 3.8.4
  hooks:
  - id: flake8
    language_version: python3
    additional_dependencies:
    - flake8-2020
    - flake8-docstrings
    - flake8-pytest-style
