---
branches:
  only:
  - master
jobs:
  include:
  - stage: build
    language: java
    jdk: openjdk11
    before_script: cd java
    script: make build
    cache:
      directories:
      - $HOME/.m2
    env:
    - CACHE=java
  - language: java
    jdk: openjdk11
    before_script: cd algorithms/project-euler
    script: make build
    cache:
      directories:
      - $HOME/.m2
    env:
    - CACHE="algorithms/project-euler"
  - language: rust
    before_script: cd rust/guessing_game
    cache: cargo
  - language: go
    go: "1.15"
    before_install: cd go
    script:
    - go build github.com/matihost/learning/go/cmd/http-server
    - go build github.com/matihost/learning/go/cmd/language
    - go test github.com/matihost/learning/go/pkg/language
    - ./language
    cache:
      directories:
      - $HOME/.cache/go-build  # Cache the binaries
      - $HOME/gopath/pkg/mod   # Cache the Go modules
  - language: python
    python: "3.8"
    before_install: cd python/apps/exchange-rate
    install:
    - pip3 install tox
    script:
    - make build
    - pip3 install -e .
    - exchange-rate
    cache: pip
