---
- hosts: local
  tasks:
  - name: Check mandatory variables
    fail:
      msg: Variable {{ item }} was not provided
    when: vars[item] is undefined
    loop:
    - env

  - name: Load {{ env }} variables files
    include_vars:
      dir: "{{ inventory_dir }}/{{ env }}"
      depth: 1
      extensions:
      - yaml
      - yml
  - name: Ensure Jenkins helm dependencies are in place
    k8s:
      state: present
      definition: "{{ lookup('template', '{{ files }}/prerequisites.template.yaml') }}"
  - name: Deploy latest version of Jenkins chart inside {{ namespace }} namespace
    helm_cli:
      name: ci
      chart_ref: stable/jenkins
      release_namespace: "{{ namespace }}"
      values: "{{ lookup('template', '{{ files }}/jenkins_helm.template.yaml') | from_yaml }}"
  - name: Ensure Jenkins Ingress DNS is resolvable locally
    shell: |
      INGRESS_IP=`kubectl get ingress ci-jenkins -n ci -o jsonpath="{.status..ip}"`
      CHANGED=`grep -c "${INGRESS_IP} {{ jenkins_ingress }}" /etc/hosts`
      [ "${CHANGED}" -eq 0 ]  && echo "update hosts" && sudo -E sh -c "echo \"${INGRESS_IP} {{ jenkins_ingress }}\" >> /etc/hosts" || echo "hosts already present"
    register: hosts_result
    changed_when: '"update hosts" in hosts_result.stdout'
