---
- hosts: local
  tasks:
  - name: Check mandatory variables
    fail:
      msg: Variable {{ item }} was not provided
    when: vars[item] is undefined
    loop:
    - env

  - name: Load {{ env }} variables files
    include_vars:
      dir: "{{ inventory_dir }}/{{ env }}"
      depth: 1
      extensions:
      - yaml
      - yml

  - name: Process Jobs
    include_role:
      name: setup_job
    loop: "{{ jenkins_jobs|default([]) }}"
    loop_control:
      loop_var: job
