---
# Default values for jenkins: https://raw.githubusercontent.com/helm/charts/master/stable/jenkins/values.yaml
namespaceOverride: ci

master:
  image: "mirror.gcr.io/jenkins/jenkins"
  tag: "lts"

  servicePort: 80
  serviceType: {{ jenkins_service_type|default("NodePort") }}

  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1beta1"
    hostName: {{ jenkins_ingress }}
    tls:
    - secretName: {{ jenkins_ingress }}
      hosts:
        - {{ jenkins_ingress }}

  installPlugins:
    - kubernetes:1.26.3
    - workflow-job:2.39
    - workflow-aggregator:2.6
    - credentials-binding:1.23
    - git:4.3.0
    - configuration-as-code:1.41
    - timestamper:1.11.3
    - github-branch-source:2.8.2
    - matrix-auth:2.6.1
    - prometheus:2.0.7
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "{{ jenkins_max_cpu|default('2000m') }}"
      memory: "{{ jenkins_max_memory|default('2Gi') }}"

  enableXmlConfig: true
  securityRealm: |-
    <securityRealm class="hudson.security.HudsonPrivateSecurityRealm">
      <disableSignup>true</disableSignup>
      <enableCaptcha>false</enableCaptcha>
    </securityRealm>

  # TODO Helm chart starts failing on added script approval
  # scriptApproval:
  #   - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
  #   - "new groovy.json.JsonSlurperClassic"

  initScripts:
    - |
      import jenkins.model.*
      import hudson.security.*
      def instance = Jenkins.getInstance()
      def hudsonRealm = new HudsonPrivateSecurityRealm(false)
      if (!hudsonRealm.getUser("admin")){
        hudsonRealm.createAccount("{{ jenkins_admin_username|default('admin') }}", "{{ jenkins_admin_pass|mandatory }}")
      }
      instance.save()

agent:
  image: "mirror.gcr.io/jenkins/jnlp-slave"
  tag: "alpine"
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "{{ jenkins_agent_max_cpu|default('2') }}"
      memory: "{{ jenkins_agent_max_memory|default('1Gi') }}"
