---
# Default values for jenkins: https://raw.githubusercontent.com/helm/charts/master/stable/jenkins/values.yaml
namespaceOverride: ci

master:
  image: "mirror.gcr.io/jenkins/jenkins"
  tag: "lts"

  servicePort: 80
  serviceType: {{ jenkins_service_type|default("NodePort") }}

  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1beta1"
    hostName: {{ jenkins_ingress }}
    tls:
    - secretName: {{ jenkins_ingress }}
      hosts:
        - {{ jenkins_ingress }}
        
  installPlugins:
    - kubernetes:1.21.2
    - workflow-job:2.36
    - workflow-aggregator:2.6
    - credentials-binding:1.20
    - git:4.0.0

agent:
  image: "mirror.gcr.io/jenkins/jnlp-slave"

