---
# Default values for jenkinsci/jenkins chart:
# helm show values jenkinsci/jenkins
namespaceOverride: ci

master:
  image: "mirror.gcr.io/jenkins/jenkins"
  tag: "lts"

  servicePort: 80
  serviceType: {{ jenkins_service_type|default("NodePort") }}

  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1beta1"
    hostName: {{ jenkins_ingress }}
    tls:
    - secretName: {{ jenkins_ingress }}
      hosts:
      - {{ jenkins_ingress }}

  installPlugins:
  - kubernetes:1.27.1
  - workflow-job:2.40
  - workflow-aggregator:2.6
  - credentials-binding:1.23
  - git:4.4.2
  - configuration-as-code:1.43
  - timestamper:1.11.5
  - github-branch-source:2.9.0
  - matrix-auth:2.6.2
  - prometheus:2.0.7
  - simple-theme-plugin:0.6
  - jdk-tool:1.4
  - command-launcher:1.4

  initializeOnce: true

  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "{{ jenkins_max_cpu|default('2000m') }}"
      memory: "{{ jenkins_max_memory|default('2Gi') }}"

  JCasC:
    enabled: true
    defaultConfig: true
    configScripts:
      iam: |
        jenkins:
          securityRealm:
            local:
              allowsSignup: false
              enableCaptcha: false
              users:
              - id: "admin"
                name: "{{ jenkins_admin_username|default('admin') }}"
                password: "{{ jenkins_admin_pass|mandatory }}"
              - id: "user"
                name: "user"
                password: "{{ jenkins_admin_pass|mandatory }}"
          authorizationStrategy:
            projectMatrix:
              permissions:
              - "Agent/Build:admin"
              - "Agent/Configure:admin"
              - "Agent/Connect:admin"
              - "Agent/Create:admin"
              - "Agent/Delete:admin"
              - "Agent/Disconnect:admin"
              - "Agent/ExtendedRead:admin"
              - "Agent/ExtendedRead:authenticated"
              - "Credentials/Create:admin"
              - "Credentials/Delete:admin"
              - "Credentials/ManageDomains:admin"
              - "Credentials/Update:admin"
              - "Credentials/View:admin"
              - "Job/Build:admin"
              - "Job/Cancel:admin"
              - "Job/Configure:admin"
              - "Job/Create:admin"
              - "Job/Delete:admin"
              - "Job/Discover:admin"
              - "Job/Discover:authenticated"
              - "Job/ExtendedRead:admin"
              - "Job/Move:admin"
              - "Job/Read:admin"
              - "Job/Read:authenticated"
              - "Job/Workspace:admin"
              - "Lockable Resources/Reserve:admin"
              - "Lockable Resources/Unlock:admin"
              - "Lockable Resources/View:admin"
              - "Lockable Resources/View:authenticated"
              - "Metrics/HealthCheck:admin"
              - "Metrics/ThreadDump:admin"
              - "Metrics/View:admin"
              - "Metrics/View:authenticated"
              - "Overall/Administer:admin"
              - "Overall/Read:admin"
              - "Overall/Read:authenticated"
              - "Overall/SystemRead:admin"
              - "Run/Delete:admin"
              - "Run/Replay:admin"
              - "Run/Update:admin"
              - "SCM/Tag:admin"
              - "View/Configure:admin"
              - "View/Create:admin"
              - "View/Delete:admin"
              - "View/Read:admin"
              - "View/Read:authenticated"
      welcome-message: |
        jenkins:
          systemMessage: Welcome to the Matihost CI\CD server.
      script-approval: |
        security:
          scriptApproval:
            approvedSignatures:
            - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
            - "new groovy.json.JsonSlurperClassic"
      neo-theme: |
        unclassified:
          simple-theme-plugin:
            elements:
              - cssUrl:
                  url: "https://tobix.github.io/jenkins-neo2-theme/dist/neo-light.css"
agent:
  #TODO jenkins/inbound-agent mirrored image dissapeared from mirror.gcr.io
  # image: "mirror.gcr.io/jenkins/inbound-agent"
  # tag: "4.3-4"
  image: "jenkins/inbound-agent"
  tag: "alpine"
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "{{ jenkins_agent_max_cpu|default('2') }}"
      memory: "{{ jenkins_agent_max_memory|default('1Gi') }}"
