---
- hosts: local
  gather_facts: false
  tasks:
    - name: Set initial facts
      set_fact:
        dictionaries:
          books:
            valid-k8s-name:
              title: valid k8s name
              author: matihost
            some_valid_ansible_key:
              title: Valid_ansible_key
              author: cat

    - name: Show all dictionaries
      debug:
        msg: "{{ dictionaries }}"

    - name: Set fact some_books
      set_fact:
        some_books: "{{ dictionaries.books }}"

    - name: Show books
      debug:
        msg: "{{ some_books }}"

    - name: Show all books
      include_role:
        name: show_books
      vars:
        books: "{{ some_books }}"
