# yamllint disable-file
{{- if .Values.networkPolicy.enabled }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ include "app.namespace" . }}
  name: deny-all
spec:
  podSelector: {}
  ingress: []
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ include "app.namespace" . }}
  name: {{ include "app.namespace" . }}-allow-from-all-namespaces
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector: {}
{{- if .Values.networkPolicy.externalIpRanges }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ include "app.namespace" . }}
  name: {{ include "app.name" . }}-allow-from-external-ip-ranges
spec:
  podSelector: {}
  ingress:
  - from:
{{- range .Values.networkPolicy.externalIpRanges }}
    - ipBlock:
        cidr: {{ .|quote }}
{{- end }}
{{- end }}
{{- end }}
