# yamllint disable-file
{{- $namespace := include "app.namespace" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $namespace }}:privileged
  namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.pspPrivilegedClusterRole }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default "default" }}
  namespace: {{ $namespace }}
