all:
  children:
    local:
      hosts:
        localhost:
      vars:
        files: "{{ playbook_dir }}/files"
        namespace: ci
        chart_version: "3.0.9"
        jenkins_service_type: NodePort
        use_prebuild_jenkins_image: true
        ingress_version: v1beta1
