all:
  hosts:
    localhost:
  vars:
    operator:
      hub: "gcr.io/istio-release"
      tag: "1.10.0"
    ingress_class:
      enable: true
      api_version: v1
      default: false
    ingress_gateway:
      default_dns_suffix: internal.testing.minikube
    egress_gateway:
      enable: true
