---
apiVersion: v1
kind: Pod
metadata:
  labels:
    baseos: ${BASE_OS}
  name: buildah
spec:
  containers:
  - args:
    - -c
    - while true; do sleep 1d;done
    command:
    - /bin/bash
    image: localhost/buildah:${BASE_OS}
    imagePullPolicy: Never
    name: buildah-${BASE_OS}
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "1"
