---
- hosts: local
  tasks:
  - name: Upgrade the repository cache and update all packages to latest
    apt:
      name: "*"
      state: latest
      update_cache: yes
      cache_valid_time: "{{ update_cache_timeout }}"
      force_apt_get: yes
  - name: Update all packages to the latest version
    apt:
      upgrade: dist
      force_apt_get: yes
  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
      force_apt_get: yes
  - name: Remove useless packages from the cache
    apt:
      autoclean: yes
      force_apt_get: yes
  - name: Update snap packages
    shell: snap refresh
    register: snap_result
    changed_when: not(snap_result.stderr is search('All snaps up to date.'))