jenkins_ingress: jenkins.ci.minikube
jenkins_jobs:
- name: learning
  description: Learning Multibranch Pipeline
  type: multibranch    
  git:
    scm: https://github.com/matihost/learning.git
- name: learning-github
  description: Learning GitHub Pipeline
  type: github    
  github:
    owner: matihost
    projects:
      include: '*'
      exclude: 'bento'