---
apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: CLUSTER_NAME
  git:
    syncRepo: REPO
    syncBranch: master
    secretType: gcenode
